"""Generate the README's claims, chart, methods, and quick start blocks and its images, or check
them for drift.

The images live in the repository, under ``.github/readme/``, so each commit's README shows its own.
PyPI cannot follow the relative paths; the package build rewrites them to the release tag
(``pyproject.toml``, ``[tool.hatch.metadata.hooks.fancy-pypi-readme]``). The banner does not
depend on the benchmark numbers, so only ``--banner`` redraws it.
"""

from __future__ import annotations

import argparse
import contextlib
import importlib.util
import io
import re
import runpy
import textwrap
from pathlib import Path

import numpy as np
from build_assets import site_builder

import andrey.viz

ROOT = Path(__file__).resolve().parents[1]
SITE_URL = "https://andrey.abel.ai"
IMAGES = ".github/readme"  # the README's images, relative to the repository root
BANNER = "banner.svg"


def readme_charts(summary) -> dict[str, str]:
    """The README's speedup chart in both themes, by file name."""
    builder = site_builder()
    return {
        builder.README_CHART.format(theme=theme): builder.readme_chart(summary, palette)
        for theme, palette in (("light", andrey.viz.LIGHT), ("dark", andrey.viz.DARK))
    }


def write_banner():
    """Draw the README's header banner, with the docs group's renderer."""
    spec = importlib.util.spec_from_file_location("andrey_cards", ROOT / "site" / "cards.py")
    cards = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cards)
    (ROOT / IMAGES).mkdir(parents=True, exist_ok=True)
    (ROOT / IMAGES / BANNER).write_text(cards.readme_banner())


def markers(name):
    """The comment pair around one generated README block."""
    return f"<!-- {name}:START -->", f"<!-- {name}:END -->"


def pitch_block(summary):
    """The four one-line claims under the badges, their numbers from the summary and registry."""
    text, _ = site_builder().launch_post_context(summary)
    start, end = markers("PITCH")
    return "\n".join(
        [
            start,
            "<!-- Generated by apps/build_launch.py; do not edit. -->",
            "",
            f"- **Fast**: {summary['headline']}",
            f"- **Just as accurate**: the same errors or fewer in {text['as_good']} comparisons"
            " with other packages.",
            f"- **One API**: {text['method_count']}, each one function call.",
            "- **Agent-ready**: a command line that answers in JSON, and a skill for coding"
            " agents.",
            "",
            end,
        ]
    )


def methods_block():
    """Every registered method, one row per family, experimental ones starred, from the registry."""
    builder = site_builder()
    specs = builder.list_specs()
    rows = []
    for family, label in builder.SPEC_FAMILIES.items():
        members = [s for s in specs if s.family == family]
        if not members:
            continue
        names = ", ".join(
            f"[`{s.name}`]({SITE_URL}/docs/code/generated/andrey.{s.name}.html)"
            + ("\\*" if s.status == "experimental" else "")
            for s in members
        )
        returns = ", ".join(dict.fromkeys(builder.returns_text(s) for s in members))
        rows.append(f"| {label} | {names} | {returns} |")
    start, end = markers("METHODS")
    return "\n".join(
        [
            start,
            "<!-- Generated from andrey.spec by apps/build_launch.py; do not edit. -->",
            "",
            "| Family | Methods | Returns |",
            "|---|---|---|",
            *rows,
            "",
            "\\* [Experimental](" + SITE_URL + "/docs/code/index.html#experimental-methods):",
            "no published benchmark yet, and the API may change.",
            "",
            end,
        ]
    )


QUICKSTART = """\
import andrey
from andrey.data import load_dataset
from andrey.metrics import score

sachs = load_dataset("sachs")  # {cells} cells, {proteins} proteins, and the known network
out = andrey.pc(sachs.data)    # learn a graph
print(out)

scores = score(out.structure, sachs.graph)
print({{k: round(scores[k], 2) for k in ("shd", "skeleton_precision", "skeleton_recall")}})
"""


def shd_parts(learned, truth):
    """The learned graph's differences from ``truth``, by kind, in words; they sum to its SHD."""
    est, ref = learned.to_numpy(), truth.to_numpy()
    counts = {"missing": 0, "extra": 0, "oriented": 0, "reversed": 0}
    for i, j in zip(*np.triu_indices(len(est), 1)):
        if bool(est[i, j]) != bool(ref[i, j]):
            counts["missing" if ref[i, j] else "extra"] += 1
        elif (est[i, j], est[j, i]) != (ref[i, j], ref[j, i]):
            undirected = ref[i, j] == ref[j, i]
            counts["oriented" if undirected else "reversed"] += 1
    words = {
        "missing": "are missing",
        "extra": "are extra",
        "oriented": "are oriented that the known network leaves undirected",
        "reversed": "are oriented differently",
    }
    parts = [f"{n} {words[kind]}" for kind, n in counts.items() if n]
    if not parts:
        return 0, "no differences"
    parts[0] = parts[0].replace(" ", " edges ", 1)
    return sum(counts.values()), ", and ".join(
        [", ".join(parts[:-1]), parts[-1]] if len(parts) > 1 else parts
    )


def quickstart_block():
    """The quick start's code, the output it prints when run, and what the numbers mean."""
    from andrey.core import GraphStructure
    from andrey.data import load_dataset
    from andrey.metrics import score as score_graph
    from andrey.metrics import to_cpdag

    cells, proteins = load_dataset("sachs").data.shape
    code = QUICKSTART.format(cells=cells, proteins=proteins)
    printed, run = io.StringIO(), {}
    with contextlib.redirect_stdout(printed):
        exec(compile(code, "README quick start", "exec"), run)
    sachs, learned, score = run["sachs"], run["out"].structure, run["scores"]
    n_learned, n_true = learned.to_edges().shape[0], sachs.graph.to_edges().shape[0]
    found = round(score["skeleton_precision"] * n_learned)
    total, parts = shd_parts(learned, to_cpdag(sachs.graph))
    if total != score["shd"]:
        raise ValueError(f"the SHD's parts sum to {total}, not {score['shd']}")
    empty = GraphStructure.from_numpy(
        np.zeros((proteins, proteins), dtype=np.int8), kind="cpdag", labels=sachs.feature_names
    )
    empty_shd = score_graph(empty, sachs.graph)["shd"]
    intro = (
        f"Learn the protein-signalling network of Sachs et al. (2005) from {cells} cells, and score"
        " it against the known network:"
    )
    among = "all" if found == n_learned else f"{found} of them"
    meaning = (
        f"PC finds {n_learned} edges, {among} among the known network's {n_true}. The"
        " structural Hamming distance (SHD) counts the edges to add, remove, or reorient to reach"
        f" the known network: {score['shd']} here ({parts}), and {empty_shd} for a graph with no"
        " edges."
    )
    start, end = markers("QUICKSTART")
    return "\n".join(
        [
            start,
            "<!-- Generated by apps/build_launch.py, which runs the code; do not edit. -->",
            "",
            *textwrap.wrap(intro, width=99, break_long_words=False, break_on_hyphens=False),
            "",
            "```python",
            code.rstrip("\n"),
            "```",
            "",
            "```text",
            printed.getvalue().rstrip("\n"),
            "```",
            "",
            *textwrap.wrap(meaning, width=99, break_long_words=False, break_on_hyphens=False),
            "",
            end,
        ]
    )


def chart_block(summary):
    """The speedup chart in both themes, its alt text from the same slides, and the report link."""
    builder = site_builder()
    alt = textwrap.wrap(builder.readme_chart_alt(summary), 88)
    light, dark = (builder.README_CHART.format(theme=theme) for theme in ("light", "dark"))
    start, end = markers("CHART")
    return "\n".join(
        [
            start,
            "<!-- Generated from summary.json by apps/build_launch.py; do not edit. -->",
            "",
            '<p align="center">',
            "  <picture>",
            '    <source media="(prefers-color-scheme: dark)"',
            f'      srcset="{IMAGES}/{dark}">',
            f'    <img alt="{alt[0]}',
            *(f"      {line}" for line in alt[1:-1]),
            *([f'      {alt[-1]}"'] if len(alt) > 1 else []),
            f'      src="{IMAGES}/{light}" width="100%">',
            "  </picture>",
            "</p>",
            "",
            f'<p align="center"><a href="{SITE_URL}/docs/benchmarks.html">Benchmark report</a></p>',
            "",
            end,
        ]
    )


def why_fast_block():
    """The four ideas behind the speed, one line each, for readers who cannot play the animations
    (the README, and so the package index); the guide animates each."""
    scenes = runpy.run_path(str(ROOT / "site" / "why_fast.py"))["SCENES"]
    start, end = markers("WHY_FAST")
    lines = [
        start,
        "<!-- Generated from site/why_fast.py by apps/build_launch.py; do not edit. -->",
        "",
        "Four ideas make it fast; each is animated in",
        f"[a blog post]({SITE_URL}/blog/why-andrey-is-fast.html):",
        "",
    ]
    for scene in scenes:
        text = f"- **{scene['title']}**: {scene['line']}"
        lines += textwrap.wrap(text, width=100, subsequent_indent="  ", break_on_hyphens=False)
    return "\n".join([*lines, "", end])


def update_readme(summary, check=False):
    """Replace only the generated marker blocks, or check them for drift."""
    path = ROOT / "README.md"
    source = path.read_text()
    updated = source
    blocks = (
        ("PITCH", pitch_block(summary)),
        ("CHART", chart_block(summary)),
        ("WHY_FAST", why_fast_block()),
        ("METHODS", methods_block()),
        ("QUICKSTART", quickstart_block()),
    )
    for name, block in blocks:
        start, end = markers(name)
        pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
        if len(pattern.findall(updated)) != 1:
            raise ValueError(f"README needs exactly one {name} marker block.")
        updated = pattern.sub(lambda _, block=block: block, updated)
    if check and updated != source:
        raise ValueError("README generated blocks differ from summary.json, andrey.spec, or a run.")
    if not check:
        path.write_text(updated)
    for name, chart in readme_charts(summary).items():
        target = ROOT / IMAGES / name
        if check and (not target.is_file() or target.read_text() != chart):
            raise ValueError(f"{IMAGES}/{name} differs from summary.json.")
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(chart)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--readme", action="store_true")
    parser.add_argument("--check-readme", action="store_true")
    parser.add_argument("--banner", action="store_true", help=write_banner.__doc__)
    args = parser.parse_args()
    if not (args.readme or args.check_readme or args.banner):
        parser.error("Choose --readme, --check-readme, or --banner.")
    if args.banner:
        write_banner()
    if args.readme or args.check_readme:
        builder = site_builder()
        update_readme(builder.load_summary(builder.SUMMARY), check=args.check_readme)
