"""Seeded inputs shared by baseline capture and recovery tests.

``input_sha256`` pins the generated bytes.
"""

from __future__ import annotations

import hashlib

import numpy as np


def _linear_sem(seed: int, n_samples: int, weights: list[list[float]], noise: str) -> np.ndarray:
    """Linear structural equation model ``x_j = sum_i B[j, i] x_i + e_j``.

    ``weights`` is a strictly lower-triangular ``(d, d)`` coefficient matrix, so
    the recurrence fills columns in causal order ``0 -> 1 -> ... -> d-1``.
    ``noise`` selects ``"uniform"`` (non-Gaussian, for LiNGAM) or ``"gaussian"``.
    """
    rng = np.random.default_rng(seed)
    B = np.asarray(weights, dtype=np.float64)
    d = B.shape[0]
    e = _noise(rng, (n_samples, d), noise)
    X = np.zeros((n_samples, d), dtype=np.float64)
    for j in range(d):
        X[:, j] = e[:, j] + X @ B[j]
    return X


def _noise(rng: np.random.Generator, shape: tuple[int, int], noise: str) -> np.ndarray:
    """Draw an innovation array: ``"uniform"`` (non-Gaussian) or ``"gaussian"``."""
    if noise == "uniform":
        return rng.uniform(-1.0, 1.0, size=shape)
    if noise == "gaussian":
        return rng.standard_normal(size=shape)
    raise ValueError(f"unknown noise model: {noise!r}")


def _var_process(
    seed: int,
    n_samples: int,
    B0: list[list[float]],
    A1: list[list[float]],
    noise: str,
    burn_in: int,
) -> np.ndarray:
    """Stable VAR(1) with instantaneous LiNGAM mixing:
    ``x_t = B0 x_t + A1 x_{t-1} + e_t`` solved as
    ``x_t = (I - B0)^{-1} (A1 x_{t-1} + e_t)``.

    ``B0`` is strictly lower-triangular (instantaneous causal order), ``A1`` the
    lag-1 matrix; both are chosen so the reduced-form spectral radius is < 1. A
    ``burn_in`` prefix is discarded so the returned window is stationary.
    """
    rng = np.random.default_rng(seed)
    B0a = np.asarray(B0, dtype=np.float64)
    A1a = np.asarray(A1, dtype=np.float64)
    d = B0a.shape[0]
    total = n_samples + burn_in
    e = _noise(rng, (total, d), noise)
    ib_inv = np.linalg.inv(np.eye(d) - B0a)
    X = np.zeros((total, d), dtype=np.float64)
    X[0] = ib_inv @ e[0]
    for t in range(1, total):
        X[t] = ib_inv @ (A1a @ X[t - 1] + e[t])
    return X[burn_in:]


def _varma_process(
    seed: int,
    n_samples: int,
    B0: list[list[float]],
    A1: list[list[float]],
    M1: list[list[float]],
    noise: str,
    burn_in: int,
) -> np.ndarray:
    """Stable VARMA(1,1) with instantaneous mixing:
    ``x_t = B0 x_t + A1 x_{t-1} + e_t + M1 e_{t-1}`` solved as
    ``x_t = (I - B0)^{-1} (A1 x_{t-1} + e_t + M1 e_{t-1})``.

    ``A1`` (AR) and ``M1`` (MA) are small so the process is stationary and
    invertible; the ``burn_in`` prefix is discarded.
    """
    rng = np.random.default_rng(seed)
    B0a = np.asarray(B0, dtype=np.float64)
    A1a = np.asarray(A1, dtype=np.float64)
    M1a = np.asarray(M1, dtype=np.float64)
    d = B0a.shape[0]
    total = n_samples + burn_in
    e = _noise(rng, (total, d), noise)
    ib_inv = np.linalg.inv(np.eye(d) - B0a)
    X = np.zeros((total, d), dtype=np.float64)
    X[0] = ib_inv @ e[0]
    for t in range(1, total):
        X[t] = ib_inv @ (A1a @ X[t - 1] + e[t] + M1a @ e[t - 1])
    return X[burn_in:]


def _anm_pair(seed: int, n_samples: int, x_range: float, noise_scale: float) -> np.ndarray:
    """Nonlinear additive-noise pair ``x -> y`` with ``y = x**3 + n``.

    ``x`` is a non-Gaussian (uniform) cause and ``n`` an independent uniform
    noise; the cubic makes the direction identifiable for ANM/PNL. Returns an
    ``(n_samples, 2)`` matrix with column 0 = cause, column 1 = effect.
    """
    rng = np.random.default_rng(seed)
    x = rng.uniform(-x_range, x_range, size=n_samples)
    n = rng.uniform(-noise_scale, noise_scale, size=n_samples)
    # A multiplication chain, not ``x**3``: each multiply is exactly rounded on every machine,
    # while numpy dispatches ``power`` to a SIMD kernel chosen from the host's CPU features, so the
    # cube's last bits -- and with them this case's input hash -- would vary by runner.
    y = x * x * x + n
    return np.column_stack([x, y]).astype(np.float64)


def _confounded_sem(
    seed: int,
    n_samples: int,
    weights: list[list[float]],
    noise: str,
    observed: list[int],
) -> np.ndarray:
    """Linear non-Gaussian SEM over all variables, returning only ``observed``
    columns so the dropped variables act as unobserved confounders.

    ``weights`` is strictly lower-triangular over the full order (latents first);
    projecting away the latent columns leaves confounded observed pairs for
    RCD / CAM-UV / BottomUpParceLiNGAM to recover.
    """
    X_full = _linear_sem(seed=seed, n_samples=n_samples, weights=weights, noise=noise)
    return X_full[:, list(observed)]


# Case registry: each entry fully determines a reproducible input matrix.
CASES: dict[str, dict] = {
    # Non-Gaussian linear SEM (uniform noise) - DirectLiNGAM's assumption.
    "lingam_5v_uniform": {
        "noise": "uniform",
        "seed": 20240611,
        "n_samples": 1000,
        "weights": [
            [0.0, 0.0, 0.0, 0.0, 0.0],
            [0.6, 0.0, 0.0, 0.0, 0.0],
            [0.4, 0.7, 0.0, 0.0, 0.0],
            [0.0, 0.5, 0.0, 0.0, 0.0],
            [0.0, 0.0, 0.3, 0.8, 0.0],
        ],
    },
    # Linear-Gaussian SEM - fisherz CI test (PC) and BIC score (GES).
    "gauss_5v": {
        "noise": "gaussian",
        "seed": 20240612,
        "n_samples": 1000,
        "weights": [
            [0.0, 0.0, 0.0, 0.0, 0.0],
            [0.8, 0.0, 0.0, 0.0, 0.0],
            [0.7, 0.0, 0.0, 0.0, 0.0],
            [0.0, 0.6, 0.5, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.9, 0.0],
        ],
    },
    # Stable VAR(1), non-Gaussian noise - VARLiNGAM and (linear) Granger.
    "var_4v_stable": {
        "model": "var",
        "noise": "uniform",
        "seed": 20240613,
        "n_samples": 500,
        "burn_in": 200,
        "B0": [
            [0.0, 0.0, 0.0, 0.0],
            [0.3, 0.0, 0.0, 0.0],
            [0.0, 0.4, 0.0, 0.0],
            [0.2, 0.0, 0.3, 0.0],
        ],
        "A1": [
            [0.3, 0.0, 0.0, 0.1],
            [0.0, 0.3, 0.0, 0.0],
            [0.0, 0.0, 0.3, 0.0],
            [0.1, 0.0, 0.0, 0.3],
        ],
    },
    # Stable/invertible VARMA(1,1), non-Gaussian noise - VARMALiNGAM.
    "varma_3v": {
        "model": "varma",
        "noise": "uniform",
        "seed": 20240614,
        "n_samples": 500,
        "burn_in": 200,
        "B0": [
            [0.0, 0.0, 0.0],
            [0.4, 0.0, 0.0],
            [0.2, 0.3, 0.0],
        ],
        "A1": [
            [0.3, 0.0, 0.0],
            [0.0, 0.25, 0.0],
            [0.0, 0.0, 0.3],
        ],
        "M1": [
            [0.2, 0.0, 0.0],
            [0.0, 0.2, 0.0],
            [0.0, 0.0, 0.2],
        ],
    },
    # Nonlinear additive-noise cause->effect pair - ANM and PNL.
    "anm_pair_cubic": {
        "model": "anm",
        "seed": 20240615,
        "n_samples": 200,
        "x_range": 1.0,
        "noise_scale": 0.3,
    },
    # Linear non-Gaussian SEM with a hidden confounder (column 0 dropped) -
    # CAM-UV, RCD, BottomUpParceLiNGAM. Full order: h, x0..x5; h confounds x1,x2.
    "confounded_6v": {
        "model": "confounded",
        "noise": "uniform",
        "seed": 20240616,
        "n_samples": 300,
        "observed": [1, 2, 3, 4, 5, 6],
        "weights": [
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # h  (latent)
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # x0
            [0.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # x1 <- h
            [0.6, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0],  # x2 <- h, x1
            [0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0],  # x3 <- x0
            [0.0, 0.0, 0.0, 0.8, 0.0, 0.0, 0.0],  # x4 <- x2
            [0.0, 0.0, 0.0, 0.0, 0.4, 0.3, 0.0],  # x5 <- x3, x4
        ],
    },
}


# Multi-group case registry: a list of datasets sharing one causal order (each weight matrix is
# strictly lower-triangular over the same order 0 -> ... -> d-1) but differing in edge support and
# strength -- MultiGroupDirectLiNGAM's assumption. Each group has its own seed for an independent
# noise draw.
GROUP_CASES: dict[str, dict] = {
    "mgdl_2groups": {
        "noise": "uniform",
        "n_samples": 800,
        "groups": [
            {
                "seed": 20240613,
                "weights": [
                    [0.0, 0.0, 0.0, 0.0, 0.0],
                    [0.6, 0.0, 0.0, 0.0, 0.0],
                    [0.4, 0.7, 0.0, 0.0, 0.0],
                    [0.0, 0.5, 0.0, 0.0, 0.0],
                    [0.0, 0.0, 0.3, 0.8, 0.0],
                ],
            },
            {
                "seed": 20240614,
                "weights": [
                    [0.0, 0.0, 0.0, 0.0, 0.0],
                    [0.3, 0.0, 0.0, 0.0, 0.0],
                    [0.8, 0.2, 0.0, 0.0, 0.0],
                    [0.0, 0.9, 0.0, 0.0, 0.0],
                    [0.0, 0.0, 0.5, 0.4, 0.0],
                ],
            },
        ],
    },
}


def generate(case_id: str) -> np.ndarray:
    """Return the input matrix for ``case_id`` (reproducible from its seed).

    Dispatches on the case's ``"model"`` key (default ``"linear_sem"``).
    """
    spec = CASES[case_id]
    model = spec.get("model", "linear_sem")
    if model == "linear_sem":
        return _linear_sem(
            seed=spec["seed"],
            n_samples=spec["n_samples"],
            weights=spec["weights"],
            noise=spec["noise"],
        )
    if model == "var":
        return _var_process(
            seed=spec["seed"],
            n_samples=spec["n_samples"],
            B0=spec["B0"],
            A1=spec["A1"],
            noise=spec["noise"],
            burn_in=spec["burn_in"],
        )
    if model == "varma":
        return _varma_process(
            seed=spec["seed"],
            n_samples=spec["n_samples"],
            B0=spec["B0"],
            A1=spec["A1"],
            M1=spec["M1"],
            noise=spec["noise"],
            burn_in=spec["burn_in"],
        )
    if model == "anm":
        return _anm_pair(
            seed=spec["seed"],
            n_samples=spec["n_samples"],
            x_range=spec["x_range"],
            noise_scale=spec["noise_scale"],
        )
    if model == "confounded":
        return _confounded_sem(
            seed=spec["seed"],
            n_samples=spec["n_samples"],
            weights=spec["weights"],
            noise=spec["noise"],
            observed=spec["observed"],
        )
    raise ValueError(f"unknown case model: {model!r}")


def generate_groups(case_id: str) -> list[np.ndarray]:
    """Return the list of input matrices for a multi-group ``case_id`` (one per group)."""
    spec = GROUP_CASES[case_id]
    return [
        _linear_sem(
            seed=group["seed"],
            n_samples=spec["n_samples"],
            weights=group["weights"],
            noise=spec["noise"],
        )
        for group in spec["groups"]
    ]


def domain_index(case_id: str, *, n_domains: int = 2) -> np.ndarray:
    """A deterministic ``(n_samples, 1)`` domain/context index for CDNOD over ``case_id``.

    Splits the samples into ``n_domains`` contiguous equal blocks labeled ``0..n_domains-1`` -- a
    fixed, reproducible surrogate for a nonstationary index. This case checks the output
    contract; domain-shift recovery has separate tests.
    """
    n = CASES[case_id]["n_samples"]
    c = np.zeros((n, 1), dtype=np.float64)
    block = n // n_domains
    for k in range(1, n_domains):
        c[k * block :, 0] = float(k)
    return c


def input_sha256(case_id: str) -> str:
    """SHA-256 of the case's input matrix (or all group matrices, in order, for a group case).

    Bytes are pinned little-endian (``<f8``) so the digest is identical across
    architectures (byte-identical to native float64 on little-endian hosts).
    """
    digest = hashlib.sha256()
    matrices = generate_groups(case_id) if case_id in GROUP_CASES else [generate(case_id)]
    for X in matrices:
        digest.update(np.ascontiguousarray(X, dtype="<f8").tobytes())
    return digest.hexdigest()
