"""Check Andrey's supported methods against data with a known graph before a release.

Each supported method runs on the datasets its assumptions fit: the published benchmark regimes,
generated by ``andrey.data`` at two sizes, a linear SCM on the ASIA network, and the measured Sachs
protein-signaling data. On each dataset, the method's median SHD over the draws must be below the
empty graph's and within the tolerance of its recorded baseline. ``quality_baselines.json`` holds
the baselines and, in one block, every tolerance with the reason for its size.

    uv run python -m qa.quality_gate                  # exit 1 if any check fails
    uv run python -m qa.quality_gate PC FCI
    uv run python -m qa.quality_gate --capture        # re-measure the baselines; review the diff
"""

from __future__ import annotations

import argparse
import functools
import json
import statistics
import sys
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
from threadpoolctl import threadpool_limits

import andrey
from andrey import GraphStructure, StructureOutput, data, metrics
from andrey.core import Kind
from andrey.data.latent import marginal
from andrey.data.real import SACHS_ARCS, SACHS_NODES

BASELINES = Path(__file__).parent / "quality_baselines.json"


# ==================================================================================================
# Datasets -- seeded draws of samples, each with the true DAG it came from.
# ==================================================================================================


@dataclass(frozen=True)
class Draw:
    """Samples and their true DAG. Hidden nodes come last and have no column."""

    data: np.ndarray
    truth: GraphStructure


#: The published regimes as ``andrey.data.sample_scm`` arguments: mean degree 2, standardized
#: columns, and one node in ten hidden for ``latent_gauss_er``.
REGIMES: dict[str, dict[str, str]] = {
    "linear_gauss_er": {"graph": "erdos_renyi", "noise": "gaussian"},
    "latent_gauss_er": {"graph": "erdos_renyi", "noise": "gaussian"},
    "lingam_sf": {"graph": "scale_free", "noise": "uniform"},
}

#: ``(d, n)`` for every regime. The benchmarks use ``n = 10d``, where ICA-LiNGAM scores worse than
#: the empty graph. At ``n = 50d`` every method's correct output beats it, so the check has power.
SIZES: tuple[tuple[int, int], ...] = ((20, 1000), (50, 2500))
SEEDS = range(10)
ASIA_N = 1000

#: ASIA (Lauritzen and Spiegelhalter, 1988): 8 variables and 8 arcs, the same as
#: ``andrey.data.load_dataset("asia").graph`` (a test checks). This arc order fixes each seed's
#: weights, and so the baselines.
ASIA_NODES = ("asia", "tub", "smoke", "lung", "bronc", "either", "xray", "dysp")
ASIA_ARCS = (
    ("asia", "tub"),
    ("smoke", "lung"),
    ("smoke", "bronc"),
    ("tub", "either"),
    ("lung", "either"),
    ("either", "xray"),
    ("either", "dysp"),
    ("bronc", "dysp"),
)


def regime_kwargs(regime: str, d: int, n: int, seed: int) -> dict[str, Any]:
    """Return the ``andrey.data.sample_scm`` arguments for one draw of ``regime``."""
    kwargs: dict[str, Any] = {
        **REGIMES[regime],
        "functional": "linear",
        "d": d,
        "n": n,
        "seed": seed,
        "scale": "standardize",
        "density": 2.0,
    }
    if regime == "latent_gauss_er":
        kwargs["latents"] = max(1, d // 10)
    return kwargs


def arc_indices(
    nodes: tuple[str, ...], arcs: tuple[tuple[str, str], ...]
) -> tuple[np.ndarray, np.ndarray]:
    """Return the parent and child index of each arc."""
    index = {name: i for i, name in enumerate(nodes)}
    return np.array([index[a] for a, _ in arcs]), np.array([index[b] for _, b in arcs])


def regime_draws(regime: str, d: int, n: int) -> tuple[Draw, ...]:
    samples = (data.sample_scm(**regime_kwargs(regime, d, n, s)) for s in SEEDS)
    return tuple(Draw(ds.data, ds.graph) for ds in samples)


def asia_draws(noise: str) -> tuple[Draw, ...]:
    scm = data.SCM(
        graph=data.graphs.FixedDAG(nodes=ASIA_NODES, arcs=ASIA_ARCS),
        functional=data.functional.linear(),
        noise=getattr(data.noise, noise)(),
    )
    samples = (scm.sample(n=ASIA_N, seed=s, scale="standardize") for s in SEEDS)
    return tuple(Draw(ds.data, ds.graph) for ds in samples)


def sachs_draws() -> tuple[Draw, ...]:
    """The Sachs observational rows and consensus network, downloaded once and cached."""
    sachs = data.load_dataset("sachs", as_frame=False)
    parents, children = arc_indices(SACHS_NODES, SACHS_ARCS)
    return (Draw(sachs.data, data.graphs.dag_truth(parents, children, len(SACHS_NODES))),)


DATASETS: dict[str, Callable[[], tuple[Draw, ...]]] = {
    **{
        f"{regime}_d{d}": functools.partial(regime_draws, regime, d, n)
        for regime in REGIMES
        for d, n in SIZES
    },
    "asia_gauss": functools.partial(asia_draws, "gaussian"),
    "asia_lingam": functools.partial(asia_draws, "uniform"),
    "sachs": sachs_draws,
}


@functools.cache
def draws(dataset: str) -> tuple[Draw, ...]:
    """Return the draws of ``dataset``, generated once per process."""
    return DATASETS[dataset]()


# ==================================================================================================
# Supported methods -- each one's fit, the graph class it is scored as, and where it applies.
# ==================================================================================================


@dataclass(frozen=True)
class Method:
    fit: Callable[[np.ndarray], StructureOutput]
    target: Kind  # "cpdag", "dag", or "pag": the class the SHD is measured in
    datasets: tuple[str, ...]


def _sizes(regime: str) -> tuple[str, ...]:
    return tuple(f"{regime}_d{d}" for d, _ in SIZES)


# A method applies where its assumptions hold. PC, GES, BOSS, and GRaSP assume no hidden variables,
# FCI allows them, and the LiNGAM methods need non-Gaussian noise. Sachs is measured data that fits
# each only approximately.
CPDAG_DATA = (*_sizes("linear_gauss_er"), "asia_gauss", "sachs")
PAG_DATA = (*_sizes("latent_gauss_er"), "asia_gauss", "sachs")
LINGAM_DATA = (*_sizes("lingam_sf"), "asia_lingam", "sachs")

#: Public defaults. A fixed seed pins BOSS's and GRaSP's search orders and FastICA's start.
SUPPORTED: dict[str, Method] = {
    "PC": Method(lambda x: andrey.pc(x), "cpdag", CPDAG_DATA),
    "FCI": Method(lambda x: andrey.fci(x), "pag", PAG_DATA),
    "GES": Method(lambda x: andrey.ges(x), "cpdag", CPDAG_DATA),
    "BOSS": Method(lambda x: andrey.boss(x, seed=0), "cpdag", CPDAG_DATA),
    "GRaSP": Method(lambda x: andrey.grasp(x, seed=0), "cpdag", CPDAG_DATA),
    "DirectLiNGAM": Method(lambda x: andrey.direct_lingam(x), "dag", LINGAM_DATA),
    "ICA-LiNGAM": Method(lambda x: andrey.ica_lingam(x, random_state=0), "dag", LINGAM_DATA),
}


def target_truth(truth: GraphStructure, target: Kind) -> GraphStructure:
    """Return what an estimate of class ``target`` is scored against, as in the published summary.

    A CPDAG is scored against the truth's CPDAG, a DAG against the DAG, and a PAG against the PAG
    of the observed variables.
    """
    if target == "pag":
        return marginal(truth, "pag", max_nodes=truth.n_nodes)
    if target == "cpdag":
        return metrics.to_cpdag(truth)
    return truth


def shd(estimate: object, truth: GraphStructure, target: Kind) -> int:
    """Return the SHD of ``estimate`` against ``target_truth``; a PAG counts endpoints."""
    if target == "cpdag":
        estimate = metrics.to_cpdag(estimate)
    return metrics.shd(estimate, truth, endpoint_aware=target == "pag")


def empty_graph(n_nodes: int, target: Kind) -> GraphStructure:
    return GraphStructure.from_numpy(np.zeros((n_nodes, n_nodes), dtype=np.int8), kind=target)


# ==================================================================================================
# The gate
# ==================================================================================================


@dataclass
class CellResult:
    """One method on one dataset: the SHD of each draw and of the empty graph, and both checks."""

    method: str
    dataset: str
    shd: list[int]
    empty_shd: list[int]
    baseline: float | None
    tolerance: float | None
    seconds: float = 0.0

    @property
    def median(self) -> float:
        return float(statistics.median(self.shd))

    @property
    def empty_median(self) -> float:
        return float(statistics.median(self.empty_shd))

    @property
    def failures(self) -> list[str]:
        out = []
        if not self.median < self.empty_median:
            out.append(
                f"median SHD {self.median:g} is not below the empty graph's {self.empty_median:g}"
            )
        if self.baseline is None or self.tolerance is None:
            out.append("no recorded baseline")
        elif abs(self.median - self.baseline) > self.tolerance:
            gap = self.median - self.baseline
            out.append(
                f"median SHD {self.median:g} is {abs(gap):g} {'above' if gap > 0 else 'below'} "
                f"the baseline {self.baseline:g} (tolerance {self.tolerance:g})"
                + ("" if gap > 0 else "; recapture if the change is intended")
            )
        return out

    @property
    def passed(self) -> bool:
        return not self.failures

    def describe(self, verdict: str | None = None) -> str:
        baseline = (
            "none"
            if self.baseline is None or self.tolerance is None
            else f"{self.baseline:g} ± {self.tolerance:g}"
        )
        verdict = verdict or ("PASS" if self.passed else "FAIL")
        return (
            f"[{verdict}] {self.method:12s} {self.dataset:20s} "
            f"SHD {self.median:5g}  empty {self.empty_median:5g}  baseline {baseline:9s} "
            f"{self.seconds:6.1f} s"
        )


def recorded() -> dict:
    """Return the ``supported`` block of ``quality_baselines.json``."""
    return json.loads(BASELINES.read_text())["supported"]


def evaluate(method: str, dataset: str, fit: Callable[[Draw], object] | None = None) -> CellResult:
    """Run ``method`` on each draw of ``dataset`` and check the result.

    ``fit`` replaces the method's own fit, so a test can feed the gate a chosen result. The numpy
    backend, one worker, and one BLAS thread keep the result independent of the host's devices and
    core count.
    """
    spec = SUPPORTED[method]
    run = fit or (lambda draw: spec.fit(draw.data))
    shds, empties = [], []
    start = time.perf_counter()
    with andrey.config(backend="numpy", num_workers=1), threadpool_limits(limits=1):
        for draw in draws(dataset):
            truth = target_truth(draw.truth, spec.target)
            shds.append(shd(run(draw), truth, spec.target))
            empties.append(shd(empty_graph(draw.data.shape[1], spec.target), truth, spec.target))
    ledger = recorded()
    cell = ledger["baselines"].get(method, {}).get(dataset, {})
    return CellResult(
        method=method,
        dataset=dataset,
        shd=shds,
        empty_shd=empties,
        baseline=cell.get("median_shd"),
        tolerance=ledger["tolerances"].get(method, {}).get("median_shd"),
        seconds=time.perf_counter() - start,
    )


def cells(methods: list[str] | None = None) -> list[tuple[str, str]]:
    """Return the ``(method, dataset)`` pairs of ``methods`` (default: all supported)."""
    return [(m, ds) for m in methods or list(SUPPORTED) for ds in SUPPORTED[m].datasets]


def capture(results: list[CellResult]) -> None:
    """Replace the baselines of each method in ``results``; keep every other recorded value."""
    everything = json.loads(BASELINES.read_text())
    baselines = everything["supported"]["baselines"]
    for method in {r.method for r in results}:
        baselines[method] = {}
    for r in results:
        baselines[r.method][r.dataset] = {
            "median_shd": r.median,
            "empty_median_shd": r.empty_median,
            "shd": r.shd,
        }
    everything["supported"]["baselines"] = {m: baselines[m] for m in SUPPORTED if m in baselines}
    BASELINES.write_text(_dumps(everything) + "\n")


def _dumps(obj: object, depth: int = 0) -> str:
    """JSON with one line per leaf object, so a recapture diff shows one line per changed cell."""
    if not isinstance(obj, dict) or not any(isinstance(v, dict) for v in obj.values()):
        return json.dumps(obj, ensure_ascii=False)
    pad = "  " * (depth + 1)
    items = [f"{pad}{json.dumps(k)}: {_dumps(v, depth + 1)}" for k, v in obj.items()]
    return "{\n" + ",\n".join(items) + "\n" + "  " * depth + "}"


# ==================================================================================================
# Command line
# ==================================================================================================


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Check Andrey's methods against known graphs.")
    ap.add_argument("methods", nargs="*", help="methods to check (default: all)")
    ap.add_argument("--capture", action="store_true", help="record the results as baselines")
    args = ap.parse_args(argv)

    unknown = sorted(set(args.methods) - set(SUPPORTED))
    if unknown:
        ap.error(f"unknown methods {unknown}; known: {list(SUPPORTED)}")

    print("Quality gate: median SHD over each dataset's draws, against the known graph.\n")
    results = []
    for method, dataset in cells(args.methods or None):
        results.append(evaluate(method, dataset))
        print(results[-1].describe("----" if args.capture else None), flush=True)
    if args.capture:
        capture(results)
        print(f"\nRecorded {len(results)} baselines in {BASELINES.name}; review the diff.")
        return 0
    failed = [r for r in results if not r.passed]
    for r in failed:
        for reason in r.failures:
            print(f"FAIL {r.method} on {r.dataset}: {reason}")
    print(f"\n{len(results)} checks, {len(failed)} failed.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
